Fix/Night Study and Out-goting, Out-sleeping
Team-B1ND/dodam-teacher-android-v6 pull request #56
Opened 2024-04-07 09:59 UTC by wnsgur1

심자, 외박, 외출기능 오류 수정

2024-04-07 23:34 UTC, SeokgyuYun requested changes

2024-04-07 23:34 UTC, SeokgyuYun commented on data/src/main/java/kr/hs/dgsw/smartschool/data/repository/MemberRepositoryImpl.kt
> +        remote.getMembers()
setMembers 함수인데 getMembers만 있어요. DB에 Insert해주는 코드가 필요할것 같습니다.

2024-04-07 23:34 UTC, SeokgyuYun commented on local/src/main/java/kr/hs/dgsw/smartschool/local/database/DodamTeacherDatabase.kt
> +    version = 14,
DB 버전을 12로 수정해주세요.

2024-04-07 23:35 UTC, SeokgyuYun requested changes
CI 오류를 해결해주세요.
명령어는 ./gradlew ktlintFormat 실행 후 성공하면 ./gradlew build

2024-04-08 07:15 UTC, wnsgur1 commented on data/src/main/java/kr/hs/dgsw/smartschool/data/repository/MemberRepositoryImpl.kt
> +        remote.getMembers()
DB에 Insert하는 코드 추가하였습니다

2024-04-08 10:33 UTC, SeokgyuYun approved these changes

2024-04-08 11:16 UTC, merged